//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4927
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intentor.Alchemy")]
[assembly: AssemblyDescription("Alchemy Exception Handling Library.")]
[assembly: AssemblyCompany("Intentor")]
[assembly: AssemblyProduct("Intentor.Alchemy")]
[assembly: AssemblyCopyright("Copyright © 2009 Intentor")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("94316ca4-e257-4785-8b10-a181f9d1d6ce")]
[assembly: AssemblyVersion("9.12.30.0")]
[assembly: AssemblyFileVersion("9.12.30.0")]


